# See https://mmistakes.github.io/minimal-mistakes/docs/configuration for details about the minimal-mistakes theme configuration.
# The default minimal-mistakes config is available at https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

# Required! See https://github.com/asciidoctor/jekyll-asciidoc?tab=readme-ov-file#configuration
asciidoc: {}

asciidoctor:
  attributes:
    icons: font
    source-highlighter: rouge

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-author
author:
  avatar: /assets/images/avatar.png # FIXME Replace with your avatar.
  bio: I are programmer. I make computer beep boop beep beep boop. # FIXME Replace with your bio.
  github: # FIXME Add your GitHub username or remove this line.
  linkedin: # FIXME Add your Linkedin username or remove this line.
  location: Earth, Milky Way # FIXME Replace with your location or remove this line.
  name: John Doe # FIXME Replace with your name.

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#giscus-comments
comments:
  giscus:
    category_name:
    category_id:
    discussion_term: "og:title"
    reactions_enabled: "1"
    repo_id:
    theme: light
  provider: giscus

copyright: John Doe # FIXME Replace with your name or anything that makes sense. This will appear in the blog footer.

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#front-matter-defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      classes: wide
      comments: false
      layout: single
      related: true
      share: true
      show_date: true

description: John Doe's blog # FIXME Replace with your blog description. This is only used in the blog HTML meta tags.

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#code-block-copy-button
enable_copy_code_button: true

encoding: utf-8

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-footer
footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/ # FIXME Replace with a link pointing to your GitHub profile (e.g. https://github.com/gwenneg) or remove this item.
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/ # FIXME Replace with a link pointing to your Linkedin profile (e.g. https://www.linkedin.com/in/gwenneg) or remove this item.

locale: en-US

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin
minimal_mistakes_skin: default

remote_theme: mmistakes/minimal-mistakes@4.26.2

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-repository
repository: # FIXME Add your GitHub repository full name (e.g. gwenneg/blog-jekyll-asciidoc-template).

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-search
search: true

show_excerpts: true

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-subtitle
subtitle: The newest blog ever. # FIXME Replace with your blog subtitle (optional).

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings
tag_archive:
  type: liquid
  path: /tags/

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-title
title: John Doe's blog # FIXME Replace with your blog title.

url: # FIXME Add your blog URL (e.g. https://gwenneg.github.io).
