# See https://mmistakes.github.io/minimal-mistakes/docs/configuration for details about the minimal-mistakes theme configuration.
# The default minimal-mistakes config is available at https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

# Required! See https://github.com/asciidoctor/jekyll-asciidoc?tab=readme-ov-file#configuration
asciidoc: {}

asciidoctor:
  attributes:
    icons: font
    source-highlighter: rouge

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-author
author:
  avatar: /assets/images/avatar.png # FIXME Replace with your avatar.
  bio: AppSec OSWE OSCP CISSP
#  bio: With 15 years of experience in **Application Security**, focusing on **web, mobile**, and **APIs**, I have developed deep expertise in identifying and mitigating vulnerabilities, particularly in alignment with the **OWASP Top 10** for both web and mobile security. Throughout my career, I’ve gained hands-on experience addressing real-world security challenges and hold certifications such as **OSWE**, **OSCP**, and **CISSP**, which further validate my skills. Having benefited significantly from the security community over the years, I now want to give back by publishing a course on **Android Application Security**. This course is designed specifically for beginners, with the aim of helping them build a strong foundation in mobile app security. By sharing my knowledge and practical insights, I hope to empower the next generation of security professionals and foster a more secure mobile ecosystem. # FIXME Replace with your bio.
  github: sheshakandula  # FIXME Add your GitHub username or remove this line.
  linkedin: sheshanandak/ # FIXME Add your Linkedin username or remove this line.
  location: NY/NJ # FIXME Replace with your location or remove this line.
  name: Sheshananda Reddy Kandula # FIXME Replace with your name.

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#giscus-comments
comments:
  giscus:
    category_name:
    category_id:
    discussion_term: "og:title"
    reactions_enabled: "1"
    repo_id:
    theme: light
  provider: giscus

copyright: Sheshananda Reddy Kandula # FIXME Replace with your name or anything that makes sense. This will appear in the blog footer.

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#front-matter-defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      classes: wide
      comments: false
      layout: single
      related: true
      share: true
      show_date: true

description: AppSec Mastery with Sheshananda # FIXME Replace with your blog description. This is only used in the blog HTML meta tags.

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#code-block-copy-button
enable_copy_code_button: true

encoding: utf-8

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-footer
footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/sheshakandula # FIXME Replace with a link pointing to your GitHub profile (e.g. https://github.com/gwenneg) or remove this item.
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/sheshanandak/ # FIXME Replace with a link pointing to your Linkedin profile (e.g. https://www.linkedin.com/in/gwenneg) or remove this item.

locale: en-US

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin
minimal_mistakes_skin: dark

remote_theme: mmistakes/minimal-mistakes@4.26.2
#troubleshooting
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-repository
repository: sheshakandula/sheshakandula.github.io # FIXME Add your GitHub repository full name (e.g. gwenneg/blog-jekyll-asciidoc-template).

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-search
search: true

show_excerpts: true

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-subtitle
subtitle: Eat, Learn, Sleep and Repeat # FIXME Replace with your blog subtitle (optional).

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings
tag_archive:
  type: liquid
  path: /tags/

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-title
title: AppSec Mastery with Sheshananda # FIXME Replace with your blog title.

url: https://sheshakandula.github.io # FIXME Add your blog URL (e.g. https://gwenneg.github.io).
baseurl: "/sheshakandula.github.io"
